version: '2'
services:
  app:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
        - /tmp:/tmp
    depends_on:
      - "mongo"

  mongo:
      image: mongo:2.6
      ports:
        - "27017:27017"
